spring:
  datasource:
    url: jdbc:mysql://localhost/jpa
    username: root
    password: 613387
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true